# Site settings
title: Alex "Ingshtrom" Hokanson
email: contact@alexhokanson.com
description: |
  Hey! I am Alex and this site is for all the things 
  that I hold dear to my heart. I hope you enjoy it and find it useful!
baseurl: ""
url: "https://www.alexhokanson.com"
twitter_username: ingshtrom
github_username:  ingshtrom

theme: jekyll-theme-merlot
